<div class="section">
    <h2>
        User not found
    </h2>

    <div class="section-body">
        <p>
            This user has been removed because it hasn't been updated in over a month. Type <a href="https://myanimelist.net/profile/<?php echo $viewContext->userName; ?>" target="_blank" rel="noreferrer"><?php echo $viewContext->userName; ?></a> in the search box above to see their stats.
        </p>
    </div>
</div>
