<?php if ($viewContext->contentType == 'image/png'): ?>
<?php readfile(join(DIRECTORY_SEPARATOR, [Config::$mediaDirectory, 'img', 'info-queued.png'])) ?>
<?php return ?>
<?php endif ?>

<div class="section">
	<h2>Okay!</h2>
	<div class="section-body">
		<div style="text-align: center">
		<p style="margin-bottom: 1.5em">
			Successfully added <a href="//myanimelist.net/profile/<?= $viewContext->userName ?>"><?php echo $viewContext->userName ?></a> to queue at position <?php echo $viewContext->queuePosition ?>.<br/>
			<small>Click your username above to make sure you typed it right.</small>
		</p>

		<?php
			$totalMinutes = ceil($viewContext->queuePosition * Config::$cronInterval / max(1, Config::$usersPerCronRun));
			$totalMinutes = Config::$cronInterval * ceil($totalMinutes / Config::$cronInterval);

			$wait = TextHelper::getTimeText($totalMinutes * 60, TextHelper::TIME_MINUTES);
		?>

		<p>
			Based on the queue size, looks like it&rsquo;ll take about <?= $wait ?>.</p>
			<p>
			This page will refresh automatically once your stats are ready.
		</p>
		</div>

		<script type="text/javascript">
		window.setTimeout(function()
		{
			window.location.reload();
		}, <?php echo 60000 ?>);
		</script>
	</div>
</div>
