<p>
	<a class="close"><i class="icon-close"></i></a>
	<?php if ($viewContext->filterParam == 0): ?>
		Unrated titles
	<?php else: ?>
		Titles rated with <?php echo $viewContext->filterParam ?>
	<?php endif ?>:

	<?php if (!empty($viewContext->entries)): ?>
		&nbsp;(<?php echo count($viewContext->entries) ?>)
	<?php endif ?>
</p>

<?php if ($viewContext->isPrivate): ?>
	<p>Can&rsquo;t show you titles from a private list.</p>
<?php elseif (empty($viewContext->entries)): ?>
	<?php if ($viewContext->filterParam == 0): ?>
		<p>Horray! No unrated titles.</p>
	<?php else: ?>
		<p>None!</p>
	<?php endif ?>
<?php else: ?>
	<ul>
		<?php foreach ($viewContext->entries as $entry): ?>
			<li>
				<a target="_blank" href="<?php echo $entry->mal_link ?>">
					<?php echo htmlspecialchars($entry->title) ?>
				</a>
				<span class="details">&nbsp;(<?php echo $entry->finished_duration ?> min.)</span>
			</li>
		<?php endforeach ?>
	</ul>
<?php endif ?>
