<p>
<a class="close"><i class="icon-close"></i></a>
<?php echo ucfirst(Media::toString($viewContext->media)) ?> from <a target="_blank" href="<?php if ($viewContext->media == Media::Manga) { echo 'http://myanimelist.net/people/' . $viewContext->filterParam . '/'; } else { echo 'http://myanimelist.net/anime.php?p=' . $viewContext->filterParam; } ?>">the <?php if ($viewContext->media == Media::Manga) { ?>author<?php } else { ?>studio<?php } ?></a>:
<?php
if (!empty($viewContext->entries)) {
?>
&nbsp;(<?php echo count($viewContext->entries); ?>, <?php if (!$viewContext->meanScore) { ?>none rated<?php } else { ?>mean score: <?php echo sprintf('%.02f', $viewContext->meanScore); } ?>)
<?php 
}
?>
</p>
<?php
if ($viewContext->isPrivate) {
?>
<p>Can&#39;t show you titles from a private list.</p>
<?php
} elseif (empty($viewContext->entries)) {
?>
<p>None!</p>
<?php
} else {
?>
<ul>
<?php
    foreach ($viewContext->entries as $entry) {
?>
<li>
<a target="_blank" href="<?php echo $entry->mal_link; ?>"><?php echo htmlspecialchars($entry->title); ?></a>
<span class="details">&nbsp;(<?php if ($entry->score) { ?>rated with <?php echo $entry->score; } else { ?>unrated<?php } ?>)</span>
</li>
<?php
    }
?>
</ul>
<?php
}
