<div class="section creators">
	<h2>
		<?php if ($viewContext->media == Media::Manga): ?>
			Favorite authors
		<?php elseif ($viewContext->media == Media::Anime): ?>
			Favorite studios
		<?php else: ?>
			<?php continue ?>
		<?php endif ?>
	</h2>
	<div class="section-body">
		<?php if ($viewContext->favCreators->getLargestGroupSize() == 0): ?>
			<p>Looks like there are no known creators for this user.</p>
			<p>Add a few titles and come back in <?php echo TextHelper::getTimeText($viewContext->updateWait, TextHelper::TIME_HOURS) ?>.<br>We'll be waiting for you.</p>
		<?php else: ?>
			<div class="scrollable">
				<table class="tablesorter">
					<thead>
						<tr>
							<th class="ord">#</th>
							<th class="title">Name</th>
							<th class="count" data-tooltip="Count of titles from given creator.">C</th>
							<th class="mean" data-tooltip="Mean score of given creator.">M</th>
							<th class="value" data-tooltip="Weighted score of given creator.">W</th>
							<th class="time">Time</th>
						</tr>
					</thead>
					<tbody>
						<?php $i = 1 ?>
						<?php foreach ($viewContext->favCreators->getGroupsKeys() as $creator): ?>
							<?php $entries = $viewContext->favCreators->getGroupEntries($creator) ?>
							<tr>
								<td class="ord"><?php echo $i ++ ?></td>
								<td class="title">
									<a class="entries-trigger" data-sender="creator" data-id="<?php echo $creator->mal_id ?>" href="#">
										<?php echo htmlspecialchars($creator->name) ?>
									</a>
								</td>
								<td class="count"><?php printf('%d', count($entries)) ?></td>
								<td class="mean">
									<?php if ($viewContext->creatorScores[$creator->mal_id] == 0): ?>
										-
									<?php else: ?>
										<?php printf('%.02f', $viewContext->creatorScores[$creator->mal_id]) ?>
									<?php endif ?>
								</td>
								<td class="value"><?php printf('%.02f', $viewContext->creatorValues[$creator->mal_id]) ?></td>
								<td class="time"><?php printf('%.02f', $viewContext->creatorTimeSpent[$creator->mal_id] / 60.0) ?>h</td>
							</tr>
						<?php endforeach ?>
						<tr class="entries-wrapper-row">
							<td colspan="6">
								<div class="entries-wrapper">
								</div>
							</td>
						</tr>
					</tbody>
				</table>

				<div class="clear"></div>
			</div>

		<?php endif ?>
	</div>
</div>
