<p>
    <a class="close">
        <i class="icon-close"></i>
    </a>
    <?php echo ucfirst(Media::toString($viewContext->media)); ?> from <a href="<?php if ($viewContext->media == Media::Manga): ?><?php echo 'https://myanimelist.net/people/' . $viewContext->filterParam; ?><?php else: ?><?php echo 'https://myanimelist.net/anime/producer/' . $viewContext->filterParam; ?><?php endif; ?>" target="_blank">the <?php if ($viewContext->media == Media::Manga): ?>author<?php else: ?>studio<?php endif; ?></a><?php if (!empty($viewContext->entries)): ?> (<?php echo count($viewContext->entries); ?>, <?php if (!$viewContext->meanScore): ?>none rated<?php else: ?>mean score: <?php echo sprintf('%.02f', $viewContext->meanScore); ?><?php endif; ?>)<?php endif; ?>:
</p>
<?php if ($viewContext->isPrivate): ?>
    <p>Can&#39;t show you titles from a private list.</p>
<?php elseif (empty($viewContext->entries)): ?>
    <p>None!</p>
<?php else: ?>
    <ul>
        <?php foreach ($viewContext->entries as $entry): ?>
            <li>
                <a href="<?php echo $entry->mal_link; ?>" target="_blank"><?php echo htmlspecialchars($entry->title); ?></a><span class="details">(<?php if ($entry->score): ?>rated with <?php echo $entry->score; ?><?php else: ?>unrated<?php endif; ?>)</span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>