<div class="section missing">
	<h2>
		Missing titles (<?php echo $viewContext->missingTitlesCount; ?>)
	</h2>
	<p class="undelete-msg">There are <strong>0</strong> hidden recommendations. <a href="#" class="undelete-trigger">Show them</a></p>
	<p class="center">Hide relation type: <a href="#" class="delete-trigger-alt-setting">Alt. setting</a> &#8226; <a href="#" class="delete-trigger-alt-version">Alt. version</a> &#8226; <a href="#" class="delete-trigger-summary">Summary</a> &#8226; <a href="#" class="delete-trigger-spin-off">Spin-off</a> &#8226; <a href="#" class="delete-trigger-character">Character</a> &#8226; <a href="#" class="delete-trigger-other">Other</a></p>
	<div class="section-body">
		<?php if ($viewContext->private): ?>
			<p>Same as above&hellip;</p>
		<?php elseif (empty($viewContext->missingTitles)): ?>
			<p>Yay! No missing relations!</p>
		<?php else: ?>
			<table>
				<thead>
					<tr>
						<th class="subject">You've <?php echo $viewContext->media == Media::Anime ? 'watched' : 'read' ?> this&hellip;</th>
						<th class="proposed">&hellip;so you might want to check this:</th>
					</tr>
				</thead>
				<?php foreach ($viewContext->missingTitles as $entry): ?>
					<tbody>
						<tr>
							<td class="subject">
								<ul>
									<li>
										<a target="_blank" href="<?php echo $entry->mal_link ?>" title="<?php echo htmlspecialchars($entry->title) ?>" rel="noreferrer">
											<?php if ($entry->status == UserListStatus::Completing): ?>
												<i data-tooltip="Completing" class="left icon-status-completing"></i>
											<?php elseif ($entry->publishing_status == MediaStatus::NotYetPublished): ?>
												<i data-tooltip="Not yet <?php echo $viewContext->media == Media::Anime ? 'aired' : 'published' ?>" class="left icon-not-yet-aired"></i>
											<?php else: ?>
												<i class="left icon-empty"></i>
											<?php endif ?>
											<?php echo htmlspecialchars($entry->title) ?>
										</a>
									</li>
								</ul>
							</td>
							<td class="proposed">
								<ul>
									<?php foreach ($entry->relations as $entry): ?>
										<li data-id="<?php echo Media::toString($entry->media) . $entry->mal_id ?>">
											<?php if ($entry->publishing_status == MediaStatus::NotYetPublished): ?>
												<i data-tooltip="Not yet <?php echo $viewContext->media == Media::Anime ? 'aired' : 'published' ?>" class="left icon-not-yet-aired"></i>
											<?php else: ?>
												<i class="left icon-empty"></i>
											<?php endif ?>
											<a href="#" class="delete-trigger">
												<i data-tooltip="Hide" class="right icon-small-close"></i>
											</a>
											<a data-tooltip="<?php echo ucfirst(MediaRelation::toString($entry->relation_type)) ?>" href="<?php echo $entry->mal_link ?>" title="<?php echo htmlspecialchars($entry->title) ?>" target="_blank" rel="noreferrer">
												<?php echo htmlspecialchars($entry->title) ?>
											</a>
										</li>
									<?php endforeach ?>
								</ul>
							</td>
						</tr>
					</tbody>
				<?php endforeach ?>
			</table>
		<?php endif ?>
	</div>
</div>
