<p>
	<a class="close"><i class="icon-close"></i></a>
	<?php if ($viewContext->filterParam == '?'): ?>
		<?php echo ucfirst(Media::toString($viewContext->media)) ?> from unknown decade
	<?php else: ?>
		<?php echo ucfirst(Media::toString($viewContext->media)) ?> from <?php echo $viewContext->filterParam ?>s
	<?php endif ?>:

	<?php if (!empty($viewContext->entries)): ?>
		&nbsp;(<?php echo count($viewContext->entries) ?>
		<?php if (!$viewContext->meanScore): ?>
			, none rated
		<?php else: ?>
			, mean score: <?php echo sprintf('%.02f', $viewContext->meanScore) ?>
		<?php endif ?>)
	<?php endif ?>
</p>

<?php if ($viewContext->isPrivate): ?>
	<p>Can&rsquo;t show you titles from a private list.</p>
<?php elseif (empty($viewContext->entries)): ?>
	<p>None!</p>
<?php else: ?>
	<ul>
		<?php foreach ($viewContext->entries as $entry): ?>
			<li>
				<a target="_blank" href="<?php echo $entry->mal_link ?>">
					<?php echo htmlspecialchars($entry->title) ?>
				</a>
				<span class="details">&nbsp;(<?php echo $entry->score ? 'rated with ' . $entry->score : 'unrated' ?>)</span>
			</li>
		<?php endforeach ?>
	</ul>
<?php endif ?>
